language: java

jdk:
- openjdk8

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -ppassword
- sudo service mysql restart
- mysql -e 'CREATE DATABASE pandaria;' -u root -ppassword

before_script:
- mongo admin --eval 'db.createUser({user:"root",pwd:"password",roles:["root"]});'

script:
  - "./gradlew clean build -x signArchives"

dist: xenial

services:
- mysql
- mongodb

sudo: required
addons:
  chrome: stable
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
